INSERT INTO tree (tree) VALUES ('Walnut');
INSERT INTO tree (tree) VALUES ('Oak');
INSERT INTO tree (tree) VALUES ('Poplar');
INSERT INTO tree (tree) VALUES ('Ash');
INSERT INTO tree (tree) VALUES ('Birch');
INSERT INTO tree (tree) VALUES ('Sycamore');
INSERT INTO tree (tree) VALUES ('Maple');
INSERT INTO tree (tree) VALUES ('Pine');
INSERT INTO tree (tree) VALUES ('Cedar');
INSERT INTO tree (tree) VALUES ('Aspen');
INSERT INTO tree (tree) VALUES ('Black Cherry');
INSERT INTO tree (tree) VALUES ('Black Oak');
INSERT INTO tree (tree) VALUES ('Chestnut');
INSERT INTO tree (tree) VALUES ('Douglas Fir');
INSERT INTO tree (tree) VALUES ('Eastern Hemlock');
INSERT INTO tree (tree) VALUES ('Eastern White Pine');
INSERT INTO tree (tree) VALUES ('Jack Pine');
INSERT INTO tree (tree) VALUES ('Lodgepole Pine');
INSERT INTO tree (tree) VALUES ('Ponderosa Pine');
INSERT INTO tree (tree) VALUES ('Red Alder');
INSERT INTO tree (tree) VALUES ('Red Maple');
INSERT INTO tree (tree) VALUES ('Red Oak');
INSERT INTO tree (tree) VALUES ('Red Pine');
INSERT INTO tree (tree) VALUES ('Southern Yellow Pine');
INSERT INTO tree (tree) VALUES ('Spruce');
INSERT INTO tree (tree) VALUES ('Subalpine Fir');
INSERT INTO tree (tree) VALUES ('Sugar Maple');
INSERT INTO tree (tree) VALUES ('Western Hemlock');
INSERT INTO tree (tree) VALUES ('Western White Pine');
INSERT INTO tree (tree) VALUES ('White Fir');
INSERT INTO tree (tree) VALUES ('White Oak');
INSERT INTO tree (tree) VALUES ('White Pine');
INSERT INTO tree (tree) VALUES ('Yellow Poplar');